models: ["NorESM2-LM"]
downloader_kwargs:
  vars: ["CO2"] # , "SO2", "BC", "CH4"] # "tas", "pr"
  experiments: ["ssp119", "ssp126", "ssp245", "ssp370", "ssp585"] # "historical"
  data_dir: "/d3/lutjens/bc3/data/raw"
  download_biomassburning: False  # get biomassburning data for input4mips